name: deploy to beanstalk
#on:
#  push:
#    tags:
#      - '*'
on: workflow_dispatch
  inputs:
    versionLabel:
      required: true
      description: バージョンラベル
      default: app-d54f-201001_154513

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Create source bundle
        run: zip -r source_bundle.jar build/libs/booking_map.jar .ebextensions

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v11
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: booking_map
          environment_name: booking-map-dev
          version_label: ${{ github.versionLabel }}
          region: ap-northeast-1
          deployment_package: source_bundle.jar
