name: Manual Trigger

on:
  workflow_dispatch:
    inputs:
      logLevel:
        required: true
        description: ログレベル
        default: warning
      tags:

jobs:
  printInputs:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "テスト"